///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GitProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6f27a602-fa04-40a2-94a5-9857a548990a")]
    public partial class GitProjectRepository : RepoGenBaseFolder
    {
        static GitProjectRepository instance = new GitProjectRepository();
        GitProjectRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        GitProjectRepositoryFolders.RxMainFrame1AppFolder _rxmainframe1;

        /// <summary>
        /// Gets the singleton class instance representing the GitProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("6f27a602-fa04-40a2-94a5-9857a548990a")]
        public static GitProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitProjectRepository() 
            : base("GitProjectRepository", "/", null, 0, false, "6f27a602-fa04-40a2-94a5-9857a548990a", ".\\RepositoryImages\\GitProjectRepository6f27a602.rximgres")
        {
            _rxmainframe = new GitProjectRepositoryFolders.RxMainFrameAppFolder(this);
            _rxmainframe1 = new GitProjectRepositoryFolders.RxMainFrame1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6f27a602-fa04-40a2-94a5-9857a548990a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("311b047d-ef81-4614-b294-436cbe20d9bf")]
        public virtual GitProjectRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The RxMainFrame1 folder.
        /// </summary>
        [RepositoryFolder("6fe3dbc0-54e4-448a-8b3e-1ab8ac554c4c")]
        public virtual GitProjectRepositoryFolders.RxMainFrame1AppFolder RxMainFrame1
        {
            get { return _rxmainframe1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GitProjectRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("311b047d-ef81-4614-b294-436cbe20d9bf")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxbuttonexitInfo;
            RepoItemInfo _resetInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "311b047d-ef81-4614-b294-436cbe20d9bf", "")
            {
                _rxbuttonexitInfo = new RepoItemInfo(this, "RxButtonExit", "button[@controlname='RxButtonExit']", 30000, null, "aa1418fe-615a-472c-8279-cfa9531ce095");
                _resetInfo = new RepoItemInfo(this, "Reset", "?/?/tabpage[@controlname='RxTabIntroduction']/link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "331dcd92-06d4-4958-8251-49fb106513b4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("311b047d-ef81-4614-b294-436cbe20d9bf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("311b047d-ef81-4614-b294-436cbe20d9bf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxButtonExit item.
            /// </summary>
            [RepositoryItem("aa1418fe-615a-472c-8279-cfa9531ce095")]
            public virtual Ranorex.Button RxButtonExit
            {
                get
                {
                    return _rxbuttonexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RxButtonExit item info.
            /// </summary>
            [RepositoryItemInfo("aa1418fe-615a-472c-8279-cfa9531ce095")]
            public virtual RepoItemInfo RxButtonExitInfo
            {
                get
                {
                    return _rxbuttonexitInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("331dcd92-06d4-4958-8251-49fb106513b4")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("331dcd92-06d4-4958-8251-49fb106513b4")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }
        }

        /// <summary>
        /// The RxMainFrame1AppFolder folder.
        /// </summary>
        [RepositoryFolder("6fe3dbc0-54e4-448a-8b3e-1ab8ac554c4c")]
        public partial class RxMainFrame1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _resetInfo;

            /// <summary>
            /// Creates a new RxMainFrame1  folder.
            /// </summary>
            public RxMainFrame1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame1", "/form[@controltypename='RxMainFrame']", parentFolder, 30000, null, true, "6fe3dbc0-54e4-448a-8b3e-1ab8ac554c4c", "")
            {
                _resetInfo = new RepoItemInfo(this, "Reset", "?/?/tabpage[1]/link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "8c7fb77e-a57f-43e2-9d7f-9676aaa72ba0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6fe3dbc0-54e4-448a-8b3e-1ab8ac554c4c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6fe3dbc0-54e4-448a-8b3e-1ab8ac554c4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("8c7fb77e-a57f-43e2-9d7f-9676aaa72ba0")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("8c7fb77e-a57f-43e2-9d7f-9676aaa72ba0")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
