///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GitProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6f27a602-fa04-40a2-94a5-9857a548990a")]
    public partial class GitProjectRepository : RepoGenBaseFolder
    {
        static GitProjectRepository instance = new GitProjectRepository();

        /// <summary>
        /// Gets the singleton class instance representing the GitProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("6f27a602-fa04-40a2-94a5-9857a548990a")]
        public static GitProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitProjectRepository() 
            : base("GitProjectRepository", "/", null, 0, false, "6f27a602-fa04-40a2-94a5-9857a548990a", ".\\RepositoryImages\\GitProjectRepository6f27a602.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6f27a602-fa04-40a2-94a5-9857a548990a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GitProjectRepositoryFolders
    {
    }
#pragma warning restore 0436
}
